@startuml
title Audit Log Operations

actor Client as Client
participant "Express Server" as Server
participant "Router" as Router
participant "Controller" as Controller
participant "Model" as Model
participant "AuditLog Model" as AuditModel
database "«MongoDB»\n:AuditLogs" as AuditDatabase

Client -> Server: API Request
Server -> Router: app.use()
Router -> Controller: function()
== If function is working correctly ==
Controller -> AuditModel: create new audit log
AuditModel -> AuditDatabase: AuditLogSchema
Controller -> Server: Response 200
Server -> Client: Response 200

@enduml