@startuml
title Delete a Car

actor Admin
participant "Express Server" as Server
participant "Car Router" as Router
participant "Car Controller" as Controller
participant "Car Model" as Model
database "«MongoDB»\n:cars" as Database

Admin -> Server: DELETE /api/v1/providers/:id
Server -> Router: app.use('/api/v1/providers', providers)
Router -> Controller: deleteCar(req.params.id)
Controller -> Model: findById(req.params.id)
alt Car not found
    Controller -> Server: Response 404 (Car not found)
    Server -> Admin: Response 404 (Car not found)
else Car exists
    Controller -> Model: findByIdAndDelete(req.params.id)
    Model -> Database: CarSchema
    Database --> Model: Car deleted
    Model --> Controller: return Message
    Controller -> Server: Response 200 (Car deleted)
    Server -> Admin: Response 200 (Car deleted)
end

@enduml
