@startuml
title Get a Single Car

actor Client
participant "Express Server" as Server
participant "Car Router" as Router
participant "Car Controller" as Controller
participant "Car Model" as Model
database "«MongoDB»\n:cars" as Database

Client -> Server: GET /api/v1/cars/:id
Server -> Router: app.use('/api/v1/cars', cars)
Router -> Controller: getCar(req.params.id)
Controller -> Model: findById(req.params.id)
Model -> Database: CarSchema
Database --> Model: Return car
Model --> Controller: Return car
alt Car exists
    Controller -> Server: Response 200 OK
    Server -> Client: Response JSON of car
else Car not found
    Controller -> Server: Response (404 Not Found)
    Server -> Client: Response (404 Not Found)
end
@enduml

