@startuml
title Update a Car

actor Admin
participant "Express Server" as Server
participant "Car Router" as Router
participant "Car Controller" as Controller
participant "Car Model" as Model
database "«MongoDB»\n:cars" as Database

Admin -> Server: PUT /api/v1/cars/:id
Server -> Router: app.use('/api/v1/cars', cars)
Router -> Controller: updateCar(req.params.id, req.body)
alt new VIN already exists
    Controller -> Server: Response 400 (VIN already registered)
    Server -> Admin: Response 400 (VIN already registered)
else VIN is unique or not provided
    Controller -> Model: findByIdAndUpdate(req.params.id, req.body)
    alt Car found
        Model -> Database: CarSchema
        Database --> Model: return Car
        Model --> Controller: return Car
        Controller -> Server: Response 200 (Car updated)
        Server -> Admin: Response 200 (Car updated)
    else Car not found
        Controller -> Server: Response 404 (Car not found)
        Server -> Admin: Response 404 (Car not found)
    end
end
@endUML