@startuml
actor User
participant "Express Server" as Server
participant "Rent Router" as Router
participant "Rent Controller" as Controller
participant "Rent Model" as RentModel
database "MongoDB" as DB

User -> Server: GET /api/v1/rents
Server -> Router: app.use('/api/v1/rents/:id',rents)
Router -> Controller: getRent()

Server -> Controller: getRent(req, res)
Controller -> RentModel: findById(req.params.id).populate(car_info, user_info)
RentModel -> DB: RentSchema
DB --> RentModel: return rent data
RentModel --> Controller: return rent data

alt Rent not found
    Controller -> Server: return 404 Not Found
    Server -> User: JSON message
else User is not admin & not rent owner
    Controller -> Server: return 403 Forbidden
    Server -> User: JSON message
else Authorized user
    Controller -> Server: return 200 OK (rent data)
    Server -> User: return rent details along with car info
end
@enduml
