@startuml

class Server as "<<Application>>\nCar Renting" {
}

class Providers as "<<Resource>>\nProviders" {
    + <<GET>> + getProviders(): Provider
    + <<POST>> + createProvider(): Provider
}
class Provider as "<<Resource>>\nProvider"{
    + <<GET>> + getProvider(): Provider
    + <<PUT>> + updateProvider(): Provider
    + <<DELETE>> + deleteProvider(): void
}
class ProviderRepresentation as "<<Representation>>\nProvider" {
    + id: String
    + name: String
    + address: String
    + tel: String
    + email: String
    + openTime: String
    + closeTime: String
}

Server --> Providers : /providers\n<<path>>
Providers --> Provider : /{providerId}\n<<path>>
Providers --> ProviderRepresentation : <<uses>>
Provider --> ProviderRepresentation : <<uses>>

class Rents as "<<Resource>>\nRents" {
    + <<GET>> + getRents(): Rent
}
class Rent as "<<Resource>>\nRent" {
    + <<GET>> + getRent(): Rent
    + <<PUT>> + updateRent(): Rent
    + <<DELETE>> + deleteRent(): void
}
class RentRepresentation as "<<Representation>>\nRent" {
    + id: String
    + car_info: Car
    + user_info: User
    + iDate: Date
    + startDate: Date
    + endDate: Date
    + status: String
}

Server --> Rents : /rents\n<<path>>
Rents --> Rent : /{rentId}\n<<path>>
Rents --> RentRepresentation : <<uses>>
Rent --> RentRepresentation : <<uses>>

class Cars as "<<Resource>>\nCars" {
    + <<GET>> + getCars(): Car
    + <<POST>> + createCar(): Car
}
class Car as "<<Resource>>\nCar" {
    + <<GET>> + getCar(): Car
    + <<PUT>> + updateCar(): Car
    + <<DELETE>> + deleteCar(): void
}
class CreateRent as "<<Resource>>\nRents" {
    + <<GET>> + getRents(): Rent
    + <<POST>> + createRents(): Rent
}

class CarRepresentation as "<<Representation>>\nCar" {
    + id: String
    + name: String
    + vin_plate: String
    + provider_info: Provider
    + capacity: Number
    + model: String
    + pricePerDay: Number
    + createdAt: Date
}

Server --> Cars : /cars\n<<path>>
Cars --> Car : /{carId}\n<<path>>
Cars --> CreateRent : /{carId}/rents\n<<path>>
CreateRent --> RentRepresentation : <<uses>>
Cars --> CarRepresentation : <<uses>>
Car --> CarRepresentation : <<uses>>


class AuditLogs as "<<Resource>>\nAuditLogs" {
    + <<GET>> + getAuditLogs(): AuditLog
}
class AuditLog as "<<Resource>>\nAuditLog" {
    + <<GET>> + getAuditLog(): AuditLog
}
class AuditLogRepresentation as "<<Representation>>\nAuditLog" {
    + id: String
    + user_info: ObjectID
    + target: String
    + target_info: ObjectID
    + timestamp: Date
    + description: String
}

Server --> AuditLogs : /auditlogs\n<<path>>
AuditLogs --> AuditLog : /{auditLogId}\n<<path>>
AuditLogs --> AuditLogRepresentation : <<uses>>
AuditLog --> AuditLogRepresentation : <<uses>>


@enduml
