@startuml

class Server as "<<Application>>\nCar Renting" {
}

class Auth as "<<Resource>>\nAuth" {
}

class Login as "<<Resource>>\nLogin" {
    <<POST>> + login(): User
}

class Logout as "<<Resource>>\nLogout" {
    <<GET>> + logout(): void
}

class Register as "<<Resource>>\nRegister" {
    <<POST>> + register(): User
}

class GetMe as "<<Resource>>\nGetMe" {
    <<GET>> + getMe(): User
}


class UserRepresentation as "<<Representation>>\nUser" {
    + id: String
    + name: String
    + tel: String
    + email: String
    + role: String
    + createdAt: Date
}

Server --> Auth : /auth\n<<path>>
Auth --> Login : /login\n<<path>>
Auth --> Logout : /logout\n<<path>>
Auth --> Register : /register\n<<path>>
Auth --> GetMe : /me\n<<path>>
Login --> UserRepresentation : <<uses>>
Logout --> UserRepresentation : <<uses>>
Register --> UserRepresentation : <<uses>>
GetMe --> UserRepresentation : <<uses>>
@endUML